#!/bin/bash
webtag="https://www.thedailystar.net"
cache="/tmp/news.cache"
cache2="/tmp/news.cache2"
echo "The Daily Star-CLI"
curl "https://www.thedailystar.net/todays-news" > $cache && clear
title="$(cat $cache | grep '</a> </td>' | cut -d '>' -f 2 | sed 's/<\/a//g' | sed 's/&#039;//g' | dmenu)"
link="$(cat $cache | grep -i "$title" | cut -d '>' -f 1 | cut -d '"' -f 2)"
curl "$webtag$link" > $cache2 && clear
rm $cache
final="$(cat $cache2 | grep "<p>" | perl -ne 'if(/<p>(.*?)<\/p>/){print "$1\t$2\n"}' | sed 's/<strong>//g' | sed 's/<\/strong>//g')"
#echo $final | tr . \\n | sed 's/$/./' | sed 's/^ //g' | head -n -1 > $cache
echo $final > $cache
less $cache
#cat $cache
#echo $final
#w3m $cache
rm $cache $cache2
